### ISSUE TITLE
REST error

### ISSUE THREAD

**Issue by andreacortis** [graknlabs/grakn-python#17]
I tried to follow the instructions on the readme, but it fails with this message. Any ideas?

```
(py36) Andreas-Air:~ andreacortis$ echo $JAVA_HOME 
/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home

(py36) Andreas-Air:grakn-dist-0.13.0 andreacortis$ ./bin/grakn.sh start
Redis is already running
Cassandra already running
Engine already running

(py36) Andreas-Air:grakn-dist-0.13.0 andreacortis$ ./bin/graql.sh -f ./examples/basic-genealogy.gql
$24816 id "1151064" (child: id "86152", parent: id "409688") isa parentship; [snip]

(py36) Andreas-Air:~ andreacortis$ ipython
Python 3.6.1 (default, Apr  4 2017, 09:40:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from grakn.client import Graph

In [2]: graph = Graph(uri='http://localhost:4567', keyspace='mygraph')

In [3]: graph.execute('insert person sub entity;')
REST error
ai.grakn.exception.GraknEngineServerException: Only "read-only" queries are allowed.
	at ai.grakn.engine.controller.GraqlController.executeGraqlGET(GraqlController.java:134)
	at spark.RouteImpl$1.handle(RouteImpl.java:61)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
Out[3]: []

```

**Comment by aelred** [comment]
Hi, I managed to reproduce this so can confirm it's a real issue.

It looks like it's actually a problem with Grakn itself: the output is coming from the `grakn.sh` command, not from the python REPL. If you start `ipython` from a different terminal, you won't see this message.

I've made a new issue on the main repo grakn-labs/grakn#1819
